# File: docker-compose.dev.yml
# Corrected Version: Uses separate named volumes for data and extensions.

version: "3.8"

services:
  cpp-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: huntmaster-cpp-dev
    ports:
      - "8080:8080"
    volumes:
      # This still mounts your source code for editing.
      - .:/workspaces/huntmaster
      # UPDATED: Separate, persistent volumes for user data and extensions.
      - vscode-user-data:/data/user-data
      - vscode-extensions:/data/extensions
    command: sleep infinity

# UPDATED: This defines the separate named volumes.
volumes:
  vscode-user-data: {}
  vscode-extensions: {}
