if(EXISTS "/mnt/e/develop/Huntmaster/huntmaster-engine/RunEngineTests[1]_tests.cmake")
  include("/mnt/e/develop/Huntmaster/huntmaster-engine/RunEngineTests[1]_tests.cmake")
else()
  add_test(RunEngineTests_NOT_BUILT RunEngineTests_NOT_BUILT)
endif()
